name: Build
on:
  push:
    paths-ignore:
      - example/**
      - README.md
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - example/**
      - README.md
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macOS-11
        go:
        - 1.17
        - 1.18
        - 1.19
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: cd example && make
      - name: vet
        run: go vet ./...
